[phases.setup]
nixPkgs = ['php82', 'composer', 'openssl']

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "mkdir -p bootstrap/cache storage/logs storage/framework/{sessions,views,cache}",
  "chmod -R 777 bootstrap/cache storage bootstrap/cache",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear"
]

  