import "./bootstrap";
import "./login.js";
import './constants.js'
import "./description_games.js"
import "./get_wishlist.js"
import "./home.js"
import "./registrazione.js"
import "./script.js"
import "./top_5.js"
